# -*- coding: utf-8 -*-
"""jarir_data_eng_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kd1DXhBqoPNR0Ch2KYSrCKFo0zwTzUnp
"""

# Install Delta Lake and logging utilities

!pip -q install pyspark delta-spark loguru

#  Imports and logging setup
import sys
import os
import shutil
import json
from datetime import datetime
import pandas as pd
from loguru import logger

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, avg, count, round, concat_ws, lit
from delta import configure_spark_with_delta_pip

# Configure Loguru output format
LOG_FORMAT = "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"
logger.remove()
logger.add(sys.stderr, format=LOG_FORMAT, level="INFO")
logger.add("pipeline_execution.log", format=LOG_FORMAT, level="INFO")

logger.info("Libraries and logging initialized.")

# Start Spark with Delta Lake support
# Spark processes data, Delta Lake provides the reliable storage layer.

builder = (
    SparkSession.builder
    .appName("JarirProductLakehousePipeline")
    .master("local[*]")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
    .config("spark.sql.warehouse.dir", "./data/warehouse")
)

spark = configure_spark_with_delta_pip(builder).getOrCreate()
spark.sparkContext.setLogLevel("ERROR")

logger.success(" Spark + Delta Lake are ready!")

# Data Ingestion: Landing Zone
#  generate two batches to test both quality gate scenarios
# 1. Failing batch with intentional errors (Completeness, Accuracy, Uniqueness, Validity)
# 2. Passing batch with fully clean and verified records

os.makedirs("landing_zone", exist_ok=True)

# Scenario A: Batch containing intentional data quality issues
faulty_batch = {
    "item_id": ["J101", "J102", "J103", "J101"],                           # Uniqueness error: duplicate J101
    "item_name": ["Apple iPad Air", None, "Wireless Mouse", "iPad Backup"], # Completeness error: missing name
    "category": ["Electronics", "Books", "Electronics", "Electronics"],
    "price": [2799.0, 65.0, -15.0, 2799.0],                                 # Accuracy / Business error: negative price
    "rating": [4.8, 4.9, 4.2, 7.5],                                         # Validity error: rating exceeds 5.0
    "description": [
        "Lightweight Apple tablet for digital design and productivity.",
        "Practical self-help book on habit building.",
        "Ergonomic wireless mouse for daily office work.",
        "Duplicate tablet record."
    ]
}

# Scenario B: Batch containing 100% clean data
clean_batch = {
    "item_id": ["J201", "J202", "J203", "J204"],
    "item_name": [
        "Python Programming Guide",
        "Noise Cancelling Headphones",
        "Daily Planner Notebook",
        "Mechanical Keyboard"
    ],
    "category": ["Books", "Electronics", "Stationery", "Electronics"],
    "price": [120.0, 850.0, 35.0, 320.0],
    "rating": [4.9, 4.7, 4.5, 4.6],
    "description": [
        "Comprehensive textbook for Python data engineering and algorithms.",
        "Wireless over-ear headphones with active noise cancellation for focus.",
        "High quality academic planner for daily scheduling and notes.",
        "Compact mechanical keyboard with responsive switches for coding."
    ]
}

# Save raw incoming files to simulate landing zone ingestion
path_fail = "landing_zone/batch_incoming_faulty.csv"
path_pass = "landing_zone/batch_incoming_clean.csv"

pd.DataFrame(faulty_batch).to_csv(path_fail, index=False)
pd.DataFrame(clean_batch).to_csv(path_pass, index=False)

logger.info(f"Raw data landed: {path_fail}")
logger.info(f"Raw data landed: {path_pass}")

# Evaluates incoming datasets across the four core dimensions:
# Completeness, Accuracy, Uniqueness, and Validity.

class DataQualityEngine:
    def __init__(self, dataframe: pd.DataFrame):
        self.df = dataframe
        self.results = {
            "timestamp": datetime.now().isoformat(),
            "metrics": {},
            "passed_all_gates": True
        }

    def run_all_checks(self) -> dict:
        logger.info("Initiating automated data quality scan...")

        # 1. COMPLETENESS: Are mandatory fields present?
        null_count = int(self.df["item_name"].isnull().sum() + self.df["item_id"].isnull().sum())
        self.results["metrics"]["completeness_null_check"] = {
            "failed_records": null_count,
            "status": "PASSED" if null_count == 0 else "FAILED"
        }

        # 2. ACCURACY / BUSINESS RULES: Does price satisfy business rules ?
        invalid_price_count = int((self.df["price"] <= 0).sum())
        self.results["metrics"]["accuracy_positive_price"] = {
            "failed_records": invalid_price_count,
            "status": "PASSED" if invalid_price_count == 0 else "FAILED"
        }

        # 3. UNIQUENESS: Are item IDs unique across the batch?
        duplicate_count = int(self.df.duplicated(subset=["item_id"]).sum())
        self.results["metrics"]["uniqueness_item_ids"] = {
            "failed_records": duplicate_count,
            "status": "PASSED" if duplicate_count == 0 else "FAILED"
        }

        # 4. VALIDITY: Are ratings within the permissible range ?
        invalid_rating_count = int((~self.df["rating"].between(1.0, 5.0)).sum())
        self.results["metrics"]["validity_rating_range"] = {
            "failed_records": invalid_rating_count,
            "status": "PASSED" if invalid_rating_count == 0 else "FAILED"
        }

        # Evaluate the overall quality gate
        for check in self.results["metrics"].values():
            if check["status"] == "FAILED":
                self.results["passed_all_gates"] = False

        return self.results

# PASS -> Transforms data and appends to Delta Lake Production Table
# FAIL -> Quarantines corrupt batch to isolation storage for investigation

DELTA_LAKE_PATH = "./data/delta/jarir_production"
QUARANTINE_PATH = "./data/quarantine_zone"

os.makedirs(QUARANTINE_PATH, exist_ok=True)

def route_batch(df_pandas: pd.DataFrame, report: dict, batch_name: str, raw_file_path: str):
    logger.info(f"Routing batch: {batch_name}")


    # PASS: Route to Delta Lake Production

    if report["passed_all_gates"]:
        logger.success(f"PASS: Batch '{batch_name}' passed all quality dimensions.")

        # Convert to Spark DataFrame
        spark_df = spark.createDataFrame(df_pandas)

        # Transformation: add context and quality metadata
        transformed_df = (
            spark_df
            .withColumn("search_context", concat_ws(" - ", col("item_name"), col("category"), col("description")))
            .withColumn("quality_status", lit("VERIFIED_CLEAN"))
        )

        # Write clean data to Delta Lake table using append mode
        transformed_df.write.format("delta").mode("append").save(DELTA_LAKE_PATH)

        print(f"\n PASS → Production Delta Lake Table committed at: {DELTA_LAKE_PATH}")

        # Clean up temporary landing file
        if os.path.exists(raw_file_path):
            os.remove(raw_file_path)

        return DELTA_LAKE_PATH


    # FAIL: to Quarantine Zone

    else:
        logger.error(f"FAIL: Batch '{batch_name}' failed quality gate.")

        # Quarantine failed batch
        timestamp_id = int(datetime.now().timestamp())
        quarantine_file = f"{QUARANTINE_PATH}/corrupt_{batch_name}_{timestamp_id}.csv"
        df_pandas.to_csv(quarantine_file, index=False)

        logger.warning(f"Corrupt batch isolated to: {quarantine_file}")
        print(f"\n FAIL → Quarantined batch isolated at: {quarantine_file}")

        # Clean up temporary landing file
        if os.path.exists(raw_file_path):
            os.remove(raw_file_path)

        return quarantine_file

# Execution & Demonstration of Pass/Fail Cases

# Case 1: Run Quality Gate on the Faulty Batch (Expected: FAIL)


print("TEST CASE 1: FAULTY BATCH (EXPECTED: FAIL)")


df_faulty = pd.read_csv("landing_zone/batch_incoming_faulty.csv")
dq_engine_faulty = DataQualityEngine(df_faulty)
report_faulty = dq_engine_faulty.run_all_checks()

print("\n--- Quality Inspection Report (Faulty Batch) ---")
print(json.dumps(report_faulty, indent=4))

dest_fail = route_batch(df_faulty, report_faulty, "batch_faulty", "landing_zone/batch_incoming_faulty.csv")

# Case 2: Run Quality Gate on the Clean Batch (Expected: PASS)


print("TEST CASE 2: CLEAN BATCH (EXPECTED: PASS)")


df_clean = pd.read_csv("landing_zone/batch_incoming_clean.csv")
dq_engine_clean = DataQualityEngine(df_clean)
report_clean = dq_engine_clean.run_all_checks()

print("\n--- Quality Inspection Report (Clean Batch) ---")
print(json.dumps(report_clean, indent=4))

dest_pass = route_batch(df_clean, report_clean, "batch_clean", "landing_zone/batch_incoming_clean.csv")

# Analytics Output from Production Delta Lake
# Read verified records

# 1. Read validated data from Delta Lake
df_production = spark.read.format("delta").load(DELTA_LAKE_PATH)

print("PRODUCTION DELTA LAKE TABLE (TRUSTED RECORDS)")
df_production.select("item_id", "item_name", "category", "price", "rating", "quality_status").show(truncate=False)

# 2. Business Analytics Report
print("JARIR BUSINESS ANALYTICS REPORT")

analytics_report = (
    df_production.groupBy("category")
    .agg(
        count("item_id").alias("total_products"),
        round(avg("price"), 2).alias("avg_price_sar"),
        round(avg("rating"), 2).alias("avg_rating")
    )
    .orderBy(col("avg_price_sar").desc())
)

analytics_report.show()

# 3. Top Rated Recommendations
print("=== Top Rated Products (Ready for Downstream Recommendation Systems) ===")
(
    df_production
    .filter(col("rating") >= 4.5)
    .select("item_name", "category", "price", "rating")
    .show(truncate=False)
)

# Session Stop
spark.stop()
print("Pipeline execution finished successfully. Spark session stopped.")